---
title: "Resume"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

  Brittany Phillips is a junior pre-med student at The University of Texas at Austin in the process of getting a BSA in biology along with a pre-health certificate and a minor in business while doing reasearch in a soft tissue biomechanics lab. She participates heavily in intermurals including ultimate frisbee, sand/indoor volleyball, and basketball. She is also a competetive member of both the Texas Running and Texas Rock Climbing Club. In addition to her school related activities, she also works at a local climbing gym at the front desk and teaches youth after school clubs. Previously, she has worked teaching horseback riding lessons, as a cafe team member at LifeTime Fitness, and as a regular pet sitter through Rover.com.
    She has earned the 2nd year Excellence Award through her college, and has held a leadership position in the Texas Running Club as the social for the past 2 years. 
      Before med school and after her undergraduate career, she plans to take a gap year and move to Colorado where she'll gain skills and further nuture her love for helping people and the outdoors working as a wilderness EMT on the mountian. 
      
      LinkedIn Page: https://www.linkedin.com/in/brittany-phillips-garcia-0a9b4a157/
